# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
